spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/auth
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    h2:
      console:
        emabled: true
    hibernate:
      show-sql: true
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

jwt:
  header: Authorization
  prefix : "Bearer "
  secret: boardsecretentryajsldfasdfjhakshfdakjdhfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasd
  access-expiration: 86400
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace
